# Generated by Django 4.2.6 on 2023-11-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store", models.PositiveIntegerField()),
                ("item_num", models.CharField(max_length=30)),
                ("reg_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("image", models.FileField(upload_to="images")),
            ],
        ),
    ]
