# Generated by Django 4.2.6 on 2023-11-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_hotitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotitem",
            name="description",
            field=models.CharField(default="", max_length=100),
        ),
    ]
